#include <benchmark/benchmark.h>

#include "adproblem.hpp"

TDS_AD_BENCH(DIFF_NUMERICAL);
TDS_AD_BENCH(DIFF_CERES);
TDS_AD_BENCH(DIFF_STAN_REVERSE);
TDS_AD_BENCH(DIFF_STAN_FORWARD);
TDS_AD_BENCH(DIFF_CPPAD_AUTO);
TDS_AD_BENCH(DIFF_CPPAD_CODEGEN_AUTO);

// Run the benchmark
BENCHMARK_MAIN();
